from bisect import bisect, bisect_left, bisect_right
n=input()
arr=[int(i) for i in input().split()]
def length(arr):
    list_longest=[arr[0]]
    for i in arr:
        print(x)
        print(list_abs)
        print(list_longest)
        if abs(i)<a and i*list_longest[x-1]<0:
            list_longest.append(i)
            print(i)
        elif x<len(list_longest) and i*list_longest[x-1]<0:
            list_longest[x]=i 
            print(i)
        print("\n")
    return len(list_longest)
print(length(arr))
            
              